### ISSUE TITLE
Interested but need more info

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.maxadditionalparticipants#1]
Hello,
I'm very much interested in a more clever way of dealing with max.participants.
For example, for our summercamps we have a seperate capacity for boys and girls.
Another is that we would like to with a capacity of 40 we want people to be waitlisted from 35 and manually approve people. So from the frontend it is still full, but people who get our 'pending waitlist' mail, can register nonetheless.

After stumbling upon your extension, I cannot figure our what it actually does.
What do you mean by max additional participants?

With kind regards,
Richard van Oosterhout

**Comment by veda-consulting** [comment]
@magnolia61 sorry for the late response. Currently CiviCRM doesn't allow you to easily control how many participants can be booked in one booking. So the drop down normally always shows 10. Our extension allows you to control the number on a per event basis.

Let us know if you need anything else
